version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: osi-postgres
    environment:
      POSTGRES_DB: osi_platform
      POSTGRES_USER: osi_user
      POSTGRES_PASSWORD: osi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osi_user -d osi_platform"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: osi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: